// <auto-generated />
namespace BullsAndCowsASPnet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Inituserstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inituserstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202008281516535_Init users table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
